### PR TITLE
fix(types): Export equals

### PR DESCRIPTION
**Pull request by ffflorian**
This PR will fix the export in the types.

### CODE REVIEW

**Comment by andvgal** [comment]
@ffflorian  Thank you for the PR.

Please elaborate a bit more on changes of what the problem do you solve by that. I am concerned about possible backward compatibility issues for other TypeScript users.

@okuryu , as you are the original author of the file, can you please provide your code review feedback.

**Comment by okuryu** [comment]
At the time, I think I decided to use the default export by looking at [the existing JS implementation](https://github.com/futoin/util-js-hkdf/blob/fbd30f487e7a655840e616a109708c2f78bfe4da/hkdf.js#L174) and examples of [`futoin-hkdf`](https://github.com/futoin/util-js-hkdf/blame/a8460cfb6af4a217b5406f76da5b20ac9c815718/README.md#L59) and [`tsd`](https://github.com/SamVerschueren/tsd). This suggestion may be appropriate if it's an indication that my first implementation is wrong, or if the purpose is to avoid the default export.

However, I think this is a breaking change. AFAIK, people who use `futoin-hkdf` as ES Modules require to change the importing way from `import hkdf from 'futoin-hkdf'` to `import * as hkdf from 'futoin-hkdf'` (or `import hkdf = require('futoin-hkdf')`) or turn on the `esModuleInterop` configuration in the `tsconfig.json`. It may be kinder to bump the major version.

**Comment by andvgal** [comment]
Thanks @okuryu that what concerns in the PR. So, @ffflorian waiting for justification of why that is needed.

**Comment by ffflorian** [comment]
Hi @andvgal, sorry that I didn't make myself clear in the initial PR comment.

Your module [states](https://github.com/futoin/util-js-hkdf/blob/fbd30f487e7a655840e616a109708c2f78bfe4da/hkdf.js#L174) `module.exports = hkdf` and you are not using webpack or any other packer AFAIC. That means, you are not exporting a default or a named variable. This is expressed in TypeScript with `exports = hkdf` (see [TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require)).

Using `import hkdf from 'hkdf'` in TypeScript (what's currently declared in your definition file) would mean that you export your module in JavaScript the following way:

```js
module.exports = {
  default: hkdf
};
```

But this is not the case.

Now, if you don't enable `esModuleInterop` in your third-party library's TypeScript config, you can't import the module correctly since either the transpiler will throw an error when using `import hkdf = require('hkdf')` or JavaScript will throw an error when using `import hkdf from 'hkdf'` since there is no default export (as explained above).

From my point of view this is just fixing a wrong declaration so IMHO no major bump is needed since projects with enabled `esModuleInterop` won't see a difference and projects without `esModuleInterop` will now be able to use `import hkdf = require('hkdf')` instead of `const hkdf = require('hkdf')`.

**Comment by okuryu** [comment]
Thanks for your clarification! It sounds good to me.

**Comment by andvgal** [comment]
Thanks guys. That makes sense.
Released as v1.3.0

**Pull request merged**
